import React, { useState } from 'react';
import { CourseInfoForm } from './CourseInfoForm';
import { ParticipantsList } from './ParticipantsList';
import { ScheduleCalendar } from './ScheduleCalendar';
import { CourseData, CourseParticipant, LessonSchedule, CourseSettings } from '../../../types/course';
import { useCourseState } from '../../../hooks/useCourseState';
import { FiCheck, FiArrowLeft, FiArrowRight, FiSave } from 'react-icons/fi';

interface CourseSetupProps {
  onComplete: (courseData: CourseData) => void;
  onCancel?: () => void;
  initialData?: Partial<CourseData>;
}

type SetupStep = 'info' | 'participants' | 'schedule' | 'settings' | 'review';

const defaultSettings: CourseSettings = {
  minimumAttendancePercentage: 75,
  allowManualAdjustments: true,
  autoGenerateDocuments: true,
  emailNotifications: false,
  backupFrequency: 'weekly',
};

export const CourseSetup: React.FC<CourseSetupProps> = ({
  onComplete,
  onCancel,
  initialData,
}) => {
  const [currentStep, setCurrentStep] = useState<SetupStep>('info');
  const [courseInfo, setCourseInfo] = useState(initialData?.courseInfo || null);
  const [participants, setParticipants] = useState<CourseParticipant[]>(
    initialData?.participants || []
  );
  const [schedule, setSchedule] = useState<LessonSchedule[]>(
    initialData?.schedule || []
  );
  const [settings, setSettings] = useState<CourseSettings>(
    initialData?.settings || defaultSettings
  );

  const { createCourse, updateCourse, isLoading, error } = useCourseState();

  const steps = [
    { id: 'info', label: 'Informazioni', completed: !!courseInfo },
    { id: 'participants', label: 'Partecipanti', completed: participants.length > 0 },
    { id: 'schedule', label: 'Calendario', completed: schedule.length > 0 },
    { id: 'settings', label: 'Impostazioni', completed: true },
    { id: 'review', label: 'Riepilogo', completed: false },
  ];

  const currentStepIndex = steps.findIndex(step => step.id === currentStep);
  const canGoNext = steps[currentStepIndex]?.completed || false;
  const canGoPrev = currentStepIndex > 0;

  const handleInfoSubmit = (data: any) => {
    setCourseInfo(data);
    setCurrentStep('participants');
  };

  const handleNext = () => {
    const nextStepIndex = currentStepIndex + 1;
    if (nextStepIndex < steps.length) {
      setCurrentStep(steps[nextStepIndex].id as SetupStep);
    }
  };

  const handlePrev = () => {
    const prevStepIndex = currentStepIndex - 1;
    if (prevStepIndex >= 0) {
      setCurrentStep(steps[prevStepIndex].id as SetupStep);
    }
  };

  const handleSaveCourse = async () => {
    if (!courseInfo) return;

    const courseData: Omit<CourseData, 'courseId' | 'metadata'> = {
      courseInfo,
      participants,
      schedule,
      settings,
    };

    try {
      if (initialData?.courseId) {
        await updateCourse({
          ...courseData,
          courseId: initialData.courseId,
          metadata: initialData.metadata!,
        });
      } else {
        await createCourse(courseData);
      }
      onComplete(courseData as CourseData);
    } catch (error) {
      console.error('Error saving course:', error);
    }
  };

  const renderStepContent = () => {
    switch (currentStep) {
      case 'info':
        return (
          <CourseInfoForm
            initialData={courseInfo || undefined}
            onSubmit={handleInfoSubmit}
            onCancel={onCancel}
            isLoading={isLoading}
          />
        );

      case 'participants':
        return (
          <ParticipantsList
            participants={participants}
            onParticipantsChange={setParticipants}
            isLoading={isLoading}
          />
        );

      case 'schedule':
        return courseInfo ? (
          <ScheduleCalendar
            startDate={courseInfo.startDate}
            endDate={courseInfo.endDate}
            schedule={schedule}
            onScheduleChange={setSchedule}
            isLoading={isLoading}
          />
        ) : null;

      case 'settings':
        return (
          <div className="settings-form">
            <h3>Impostazioni Corso</h3>
            
            <div className="settings-grid">
              <div className="setting-group">
                <label htmlFor="attendance-percentage">
                  Percentuale Minima Presenza (%)
                </label>
                <input
                  id="attendance-percentage"
                  type="number"
                  min="0"
                  max="100"
                  value={settings.minimumAttendancePercentage}
                  onChange={(e) => setSettings({
                    ...settings,
                    minimumAttendancePercentage: parseInt(e.target.value) || 0
                  })}
                />
                <small>Percentuale minima di presenza richiesta per considerare un partecipante presente</small>
              </div>

              <div className="setting-group">
                <label>
                  <input
                    type="checkbox"
                    checked={settings.allowManualAdjustments}
                    onChange={(e) => setSettings({
                      ...settings,
                      allowManualAdjustments: e.target.checked
                    })}
                  />
                  Consenti Modifiche Manuali
                </label>
                <small>Permetti di modificare manualmente le ore di presenza</small>
              </div>

              <div className="setting-group">
                <label>
                  <input
                    type="checkbox"
                    checked={settings.autoGenerateDocuments}
                    onChange={(e) => setSettings({
                      ...settings,
                      autoGenerateDocuments: e.target.checked
                    })}
                  />
                  Generazione Automatica Documenti
                </label>
                <small>Genera automaticamente i Moduli B dopo l'elaborazione CSV</small>
              </div>

              <div className="setting-group">
                <label>
                  <input
                    type="checkbox"
                    checked={settings.emailNotifications}
                    onChange={(e) => setSettings({
                      ...settings,
                      emailNotifications: e.target.checked
                    })}
                  />
                  Notifiche Email
                </label>
                <small>Invia notifiche email per eventi importanti</small>
              </div>

              <div className="setting-group">
                <label htmlFor="backup-frequency">Frequenza Backup</label>
                <select
                  id="backup-frequency"
                  value={settings.backupFrequency}
                  onChange={(e) => setSettings({
                    ...settings,
                    backupFrequency: e.target.value as 'daily' | 'weekly' | 'manual'
                  })}
                >
                  <option value="daily">Giornaliero</option>
                  <option value="weekly">Settimanale</option>
                  <option value="manual">Manuale</option>
                </select>
                <small>Frequenza di backup automatico dei dati</small>
              </div>
            </div>
          </div>
        );

      case 'review':
        return (
          <div className="review-section">
            <h3>Riepilogo Corso</h3>
            
            {courseInfo && (
              <div className="review-card">
                <h4>Informazioni Corso</h4>
                <div className="review-content">
                  <p><strong>Nome:</strong> {courseInfo.name}</p>
                  <p><strong>Periodo:</strong> {courseInfo.startDate} - {courseInfo.endDate}</p>
                  <p><strong>Docente:</strong> {courseInfo.instructor.name} ({courseInfo.instructor.email})</p>
                  <p><strong>Responsabile:</strong> {courseInfo.coordinator.name} ({courseInfo.coordinator.email})</p>
                </div>
              </div>
            )}

            <div className="review-card">
              <h4>Partecipanti ({participants.length})</h4>
              <div className="review-content">
                {participants.slice(0, 5).map((participant, index) => (
                  <p key={participant.id}>
                    {index + 1}. {participant.name} ({participant.email})
                  </p>
                ))}
                {participants.length > 5 && (
                  <p>... e altri {participants.length - 5} partecipanti</p>
                )}
              </div>
            </div>

            <div className="review-card">
              <h4>Calendario ({schedule.length} lezioni)</h4>
              <div className="review-content">
                {schedule.slice(0, 3).map((lesson) => (
                  <p key={lesson.date}>
                    {lesson.date} - {lesson.lessonType} 
                    {lesson.subject && ` (${lesson.subject})`}
                  </p>
                ))}
                {schedule.length > 3 && (
                  <p>... e altre {schedule.length - 3} lezioni</p>
                )}
              </div>
            </div>

            <div className="review-card">
              <h4>Impostazioni</h4>
              <div className="review-content">
                <p><strong>Presenza minima:</strong> {settings.minimumAttendancePercentage}%</p>
                <p><strong>Modifiche manuali:</strong> {settings.allowManualAdjustments ? 'Sì' : 'No'}</p>
                <p><strong>Generazione automatica:</strong> {settings.autoGenerateDocuments ? 'Sì' : 'No'}</p>
                <p><strong>Backup:</strong> {settings.backupFrequency}</p>
              </div>
            </div>
          </div>
        );

      default:
        return null;
    }
  };

  return (
    <div className="course-setup">
      <div className="setup-header">
        <h1>{initialData ? 'Modifica Corso' : 'Nuovo Corso'}</h1>
        <div className="steps-indicator">
          {steps.map((step, index) => (
            <div
              key={step.id}
              className={`step ${currentStep === step.id ? 'active' : ''} ${step.completed ? 'completed' : ''}`}
              onClick={() => step.completed && setCurrentStep(step.id as SetupStep)}
            >
              <div className="step-number">
                {step.completed ? <FiCheck /> : index + 1}
              </div>
              <span className="step-label">{step.label}</span>
            </div>
          ))}
        </div>
      </div>

      {error && (
        <div className="error-banner">
          <p>{error}</p>
        </div>
      )}

      <div className="setup-content">
        {renderStepContent()}
      </div>

      {currentStep !== 'info' && (
        <div className="setup-navigation">
          <button
            onClick={handlePrev}
            disabled={!canGoPrev || isLoading}
            className="btn btn-secondary"
          >
            <FiArrowLeft /> Indietro
          </button>

          <div className="nav-actions">
            {currentStep === 'review' ? (
              <button
                onClick={handleSaveCourse}
                disabled={isLoading}
                className="btn btn-success"
              >
                <FiSave /> {isLoading ? 'Salvataggio...' : 'Salva Corso'}
              </button>
            ) : (
              <button
                onClick={handleNext}
                disabled={!canGoNext || isLoading}
                className="btn btn-primary"
              >
                Avanti <FiArrowRight />
              </button>
            )}
          </div>
        </div>
      )}

    </div>
  );
};
